services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@localhost/User
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=User
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
